CareEvolution/MyDataHelpsUI

CONTRIBUTING.md
README.md
src/stories/Introduction.stories.mdx

Updating documentation to link to MyDataHelps StarterKit and ui.mydatahelps.org 
Adding documentation to storybook introduction linking back to MyDataHelpsUI, MyDataHelpsStarterKit. 
Removing language from Contributing that suggests we encourage external development. 
- [X ] I have ensured no secure credentials or sensitive information remain in code, metadata, comments, etc.
- [X ] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [X ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [X ] These changes do not introduce any security risks, or any such risks have been properly mitigated.
Documentation updates that …

Updating documentation for MyDataHelpsStarterKit Release

---

package.json
src/components/presentational/Calendar/Calendar.stories.tsx
src/components/presentational/Calendar/Calendar.tsx

Adds ability to have a Calendar that starts on a different day other than Sunday.

Add option for weekStartsOn to Calendar

---

src/components/step/YouTubeStep/YouTubeStep.tsx

Small change to remove the early return when rendering Youtube steps without a videoId. Originally I had concerns about rendering the blank youtube embed page, but on reflection it looks broken and worse to have no response when inputting text or having a blank area show up on initial creation.

Show Youtube Step When No Video ID Provided

---

src/components/step/StepLayout/StepLayout.css

Small fix to properly nest and restrict scope of reset styles for StepLayout component. These still work as expected for the StepLayout and should not interfere with other non-step component styles.

Restrict StepLayout Component Reset Styles

---

src/components/presentational/SingleSurveyTask/SingleSurveyTask.css
src/components/presentational/SingleSurveyTask/SingleSurveyTask.stories.tsx
src/components/presentational/SingleSurveyTask/SingleSurveyTask.tsx

Fixes: https://github.com/CareEvolution/MyDataHelpsUI/issues/22
A small layout/CSS adjustment to prevent long task descriptions from overlapping the right chevron.

Fix long task description wrapping.

---

src/components/presentational/Histogram/Histogram.css
src/components/presentational/Histogram/Histogram.tsx
src/components/presentational/Layout/Layout.tsx
src/components/presentational/ShinyOverlay/ShinyOverlay.css

Some minor tweaks on things that would have been nice downstream.
- Histogram elements can now be clickable (to enable viewing details for instance) - this is used in Symptom Shark
- The ShinyOverlay now has pointer-events:none to prevent it from blocking clicks
- Layout can have a className

Clickable Histogram items, non-clickable overlay, layout class

---

src/components/container/RelativeActivityToday/RelativeActivityToday.css
src/components/container/RelativeActivityToday/RelativeActivityToday.stories.tsx
src/components/container/RelativeActivityToday/RelativeActivityToday.tsx
src/components/container/RelativeActivityToday/index.ts

This component can be used to visualize your activity today relative to your 30 day average.  
It takes a list of data types that you want it to display - for instance, your sleep or steps or other activity - queries the data, and displays an activity meter filled relative to your 30 day average.
This kind of component could be useful for pacing, for instance - patients with ME/CFS or Long COVID may want to ensure their steps or other activity does not go that high.
If there is no data to display for an individual metric or not at least 5 days of data to calculate a 30 day average, it will hide the metric.  If there are no metrics that would be displayed, it will hide the entire component.
Describe briefly what security risks you considered, why …

Relative Activity Today Component

---

.babelrc.json
.storybook/main.js
package-lock.json
package.json
src/stories/Introduction.stories.mdx

This upgrades MyDataHelpsUI to use the latest storybook and also upgrades it to use React 18.2.0.  I also locked emotion/react to a specific version as it seems like the latest versions have some problems/bugs that forced me to override the version in downstream projects.  
Originally I was planning to maintain compatibility with React 17, but I think we may have already accidentally broken compatibility with React 17 after I included emotion/react - as I couldn't get one of our downstream projects to run with React 17.  
Storybook added some cool new features in this release.  Each component now has a "Docs" page that shows all of the stories.  Unclear to me how they are achieving this (shadow dom?) because the stories don't seem iframed unlike the others.
As we move forward it'd be cool …

Upgrade Storybook to latest, React to 18.2.0

---

src/components/container/index.ts

In review of https://github.com/CareEvolution/MyDataHelpsUI/pull/73, we missed that the new `AppDownload` widget wasn't being added to the exports list in the `container` directory.  This meant that while it is showing up in the Storybook, you can't actually import it into an external project which uses MDHUI.

Fix missing import for AppDownload widget

---

src/helpers/daily-data-providers/garmin-sleep.ts
src/helpers/query-daily-data.ts

Garmin has a couple data idiosyncracies that I didn't account for.
It appears that Garmin can produce multiple sleep data points on a given night that overlap, e.g. 
This might just be a temporary artifact for the most recent night's sleep until Garmin syncs and removes the shorter sleep period.
To account for this state, however, I am now taking the max value.  
Previously I also missed dividing the value when we summed the values together which caused the sleep values to be massively inflated.
Assign to the appropriate reviewer(s). Minimally, a second set of …

Fix bugs with garmin sleep calculations

---

README.md
customHttp.yml

Some of the example stories use images from the assets bucket, such as this one: https://ui.mydatahelps.org/?path=/docs/surveystep-celebrationstep--docs
They're showing up as broken links due to being blocked by the CSP. I added that site to the CSP, and also made a few typo/wording tweaks to the readme.
Allowing images from our internal asset bucket does not introduce any new security risks.
The above are n/a. Must be tested with the amplify deployment of the storybook site.
No documentation needed
Assign to the appropriate reviewer(s). Minimally, a second …

Update Image CSP

---

.github/workflows/cicd-release.yml
.github/workflows/cicd-snapshot.yml
Snapshot.ps1

This change is necessary to ensure that snapshot/pre-release tags do not result in populating the `latest` version of the library. Otherwise, feature branch pre-releases can get picked up as the `latest` version.
- This change adds a further limitation to publishing to help ensure that feature branch pre-releases are not picked up as the `latest` version of the library from npm.
This change is related to build/deploy config, not the app functionality itself.  Testing of the build/deploy config will be performed as soon as changes are available on `main`.
N/A - Other than a possible update to the README to describe how to use the `Snapshot.ps1` …

Adjust cicd workflows to publish release and snapshot/prerelease tags slightly differently.

---

src/components/container/DailyDataChart/DailyDataChart.css
src/components/container/DailyDataChart/DailyDataChart.stories.tsx
src/components/container/DeviceDataMonthChart/DeviceDataMonthChart.css
src/components/presentational/Button/Button.css
src/components/presentational/Card/Card.css
src/components/presentational/DateRangeCoordinator/DateRangeCoordinator.stories.tsx
src/helpers/daily-data-providers/combined-steps.ts
src/helpers/daily-data-providers/query-all-device-data.ts
src/helpers/globalCss.ts

This takes a few of the style updates I had applied separately in https://github.com/CareEvolution/MyDataHelpsUI/pull/110 so I could release them more quickly.  It also fixes the "combined" steps provider; currently it errors if you don't have garmin or fitbit enabled for your study.  So it now checks the data collection status.
The style updates are mostly tweaking the default border radius to 12px and tweaks the default dropshadow based on some of the designs @kyledehovitz-ce has been putting out lately; so things can stay consistent / aligned.
It also changes the line-height to 1.2 instead of 1.2em, so it's applied consistently across the page (I forgot how this worked; 1.2em just sets it statically whereas 1.2 is relative to font size of the element) as this fixes an acute issue with …

Minor style updates, fixing the "combined" steps provider

---

src/components/step/ConnectDeviceAccountStep/ConnectDeviceAccountStep.stories.tsx
src/components/step/ConnectDeviceAccountStep/ConnectDeviceAccountStep.tsx
src/components/step/ConnectDeviceAccountStepContainer/ConnectDeviceAccountStepContainer.stories.tsx
src/components/step/ConnectDeviceAccountStepContainer/ConnectDeviceAccountStepContainer.tsx

This PR changes the ConnectDeviceAccountStep to use an input of `providerName` to `providerID`.
While we test #104 in QA, I realized an implicit dependency about `providerName`, which is that the FHIR provider must have its name in its key word list. @DKaczmar tried to use Fitbit Staging provider but couldn't connect to the provider. The reason was that "Fitbit Staging" was not in the keyword list.
I picked `providerName` over `providerID` at the time of writing #104 because I thought the former would be more intuitive for users. But given the additional maintenance overhead, I think now it makes more sense to just use a `providerID` for the ConnectDeviceAccountStep, which actually was the way to go in the long covid (AOU) app. 
Describe briefly …

ConnectDeviceAccountStep: Replace 'providerName' parameter with 'providerID'.

---

src/components/container/ConnectDevice/ConnectDevice.tsx
src/components/container/ExternalAccountList/ExternalAccountList.stories.tsx
src/components/container/ExternalAccountList/ExternalAccountList.tsx
src/components/container/ProviderSearch/ProviderSearch.stories.tsx
src/components/container/ProviderSearch/ProviderSearch.tsx
src/components/step/ConnectEhrStep/ConnectEhrStep.tsx

This PR changes the behavior of the app so that it always opens a window for a participant to connect to an external account. 
Previously, we would simply reload the entire window, which led participants to lose context.
Address https://github.com/CareEvolution/MyDataHelpsDesignerUI/issues/231
- Since there will be visible change for a user, it is worth mentioning the change in the release note and/or the user guide.
- Others requested by the …

Connect any external account in new window

---

src/components/presentational/DateRangeCoordinator/DateRangeCoordinator.tsx
src/components/presentational/DateRangeNavigator/DateRangeNavigator.css
src/components/presentational/DateRangeNavigator/DateRangeNavigator.tsx
src/components/symptom-shark/container/LogToday/LogToday.tsx
src/components/symptom-shark/presentational/Calendar/Calendar.tsx
src/components/symptom-shark/presentational/OverallExperienceChart/OverallExperienceChart.tsx
src/components/symptom-shark/presentational/SymptomSeverityChart/SymptomSeverityChart.tsx
src/components/symptom-shark/presentational/SymptomSeveritySummary/SymptomSeveritySummary.tsx
src/components/symptom-shark/presentational/SymptomTreatmentHistograms/SymptomTreatmentHistograms.css
src/components/symptom-shark/presentational/SymptomTreatmentHistograms/SymptomTreatmentHistograms.tsx
src/components/symptom-shark/view/CalendarView/CalendarView.tsx
src/components/symptom-shark/view/SymptomDetailView/SymptomDetailView.tsx

The symptom shark calendar view currently looks like this - the date range navigator is covering the filter buttons so you can only see a sliver of the bottom of them:
Additionally, as you scrolled down, content was scrolling behind the status bar because the "top" was set to the safe area vs. the padding-top
This is a quick fix for this issue - since this is used in the device data pages I couldn't just adjust the margin / padding / top - so this basically makes those non-sticky (which is fine...I think it's a bit awkward they were)
While an existing issue, I would like to refactor this a bit more later to use portals so that there is a single stacked "sticky" context at the top of the page.  Right now this isn't sticky if you already have a navigation bar at the top, for instance (see …

Add sticky option for date range navigator, fix Symptom Shark Calendar

---

src/components/container/AppDownload/AppDownload.css
src/components/container/AppDownload/AppDownload.stories.tsx
src/components/container/AppDownload/AppDownload.tsx
src/components/view/HomeView/HomeView.tsx

The decision of whether to use Cards or Sections is somewhat context dependent so for most components (other than, SurveyTaskList for instance; where it might render multiple cards) we don't want to include a card in the component itself.
This fixes up App Download so it's not in a card (was about to add this to the view builder and noticed this)
This also adds customizable text / title to this component
- …

Remove Card from App Download

---

src/components/step/ConnectDeviceAccountStepContainer/ConnectDeviceAccountStepContainer.tsx

The loading flag should be set to false when `getExternalAccounts` errors out. This is actually the case when a user accesses this survey step from MDHD. Due to lack of access token, `getExternalAccount` is rejected, which leaves the loading flag forever true.

ConnectDeviceAccount step: set loading flag to false on rejection

---

src/components/view/HomeView/HomeView.tsx

With upcoming changes to how project navigation works, the project header component is redundant on the out of box "home" view.  
This PR removes it from the "home" view.  

Remove project header from home view

---

src/components/container/ConnectDevice/ConnectDevice.tsx
src/components/container/ExternalAccountList/ExternalAccountList.tsx
src/components/container/ProviderSearch/ProviderSearch.tsx

Reload states after a participant successfully connects their external account.

Reload after connecting to an external account

---

src/components/view/FitbitView/FitbitView.tsx
src/components/view/GarminView/GarminView.tsx

There is a race condition with `MyDataHelps.baseUrl` not being set yet when `getFitbitProviderID` or `getGarminProviderID` are called through either the `ConnectFitbit` or `ConnectGarmin` widgets when use on the `FitbitView` or `GarminView`.  This is because no other `MyDataHelps` API call happens before `getFitbitProviderID` or `getGarminProviderID`, so `baseUrl` isn't set because no access token has been parsed yet.
The solution I'm providing here is the most straight forward.  This fix targets the views directly affected by this race condition, which does leave open the possibility for this to crop up again.  I'm certainly open to other ideas for fixing this; the only other idea I had was to push the `connect` call into the providerID getters directly - which would require them to …

Fix baseUrl race condition in providerID helpers

---

src/components/presentational/ViewHeader/ViewHeader.css
src/components/presentational/ViewHeader/ViewHeader.stories.tsx
src/components/presentational/ViewHeader/ViewHeader.tsx

This update adds an optional action icon to the ViewHeader component.
No new security risks.  This update just adds support for an optional clickable icon to an existing UI component.
No doc updates needed.

Add an optional action icon to the ViewHeader component.

---

src/components/container/SurveyTaskList/SurveyTaskList.tsx
src/components/presentational/SingleSurveyTask/SingleSurveyTask.stories.tsx
src/components/presentational/SingleSurveyTask/SingleSurveyTask.tsx

Fixes #139 
Here is another approach at fixing the issue with duplicate task survey launches.  As described previously, there are scenarios where a delay in refreshing the task list can allow a participant to launch a task survey more than once, even when the task has already been completed.
In order for refreshes to work correctly, management of the "active surveys" had to be moved up to the list itself.  This also meant that I had to move the click handling up to the list as well.  The single survey task no longer launches the survey directly. Instead, it has a click handler property and a flag for whether the task's survey is currently active (so that the spinner can be displayed).
The combination of these changes results in the clicked survey task displaying a spinner while the survey …

Prevent duplicate task survey launches.

---

src/components/presentational/CalendarDay/CalendarDay.css
src/components/presentational/CalendarDay/CalendarDay.stories.tsx
src/components/presentational/CalendarDay/CalendarDay.tsx

This branch adjusts some default styling in the `CalendarDay` component to reduce the amount of boilerplate styling needed in project specific calendar implementations.
- No security risks.  Just a styling update.

Adjust some out-of-the-box styling on the CalendarDay component.

---

src/components/step/CelebrationStep/CelebrationStep.tsx

The MDH iOS app has slightly different handling of WebViewSteps that are defined directly in a template versus ones that are specified by an external URL.  In both cases they are "preloaded" before the step actually comes in to view.  For the Celebration Step, this means that it gets an initial call to `startConfetti` when the size of the `window` is zero.  This generates all of the confetti particles in one spot, so that even when `startConfetti` is called again when the step is viewed, and the window is the right size, they start at 0,0.
I played with a few options for this, but ultimately due to timing issues, the only reliable fix was to wait to start any confetti until the window has a valid width and height.  I've tested this fix on iOS, Android, and Web and it appears to work …

Celebration Step - Fix confetti on iOS

---

src/components/presentational/CalendarDay/CalendarDay.stories.tsx
src/components/presentational/CalendarDay/CalendarDay.tsx

This branch updates the `CalendarDay` component such that it uses an `UnstyledButton` for clickable days to ensure they are included in the tab traversal of the page.
- No new security risks.  Just a rendering update.

Use an unstyled button for clickable calendar days so they are part of the tab traversal.

---

src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx
src/helpers/strings-en.ts

Remove Title from the Blood Pressure Visualization. 
- [x ] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [ x] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [ x] These changes do not introduce any security risks, or any such risks have been properly mitigated.
Assign to the appropriate reviewer(s). Minimally, …

Remove Title from BloodPressure Viz

---

src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx
src/components/container/SeverityCalendar/SeverityCalendar.tsx

InnerRef properties were added to the Severity Calendar and BP Viz. These properties are needed to get references to components
- [ x] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [x ] These changes do not introduce any security risks, or any such risks have been properly mitigated.
Assign to the appropriate reviewer(s). Minimally, a second set of eyes is needed ensure no …

Add innerRef props to SeverityCalendar and BP viz 

---

src/components/presentational/CalendarDay/CalendarDay.css
src/components/presentational/CalendarDay/CalendarDay.tsx

This branch fixes calendar day rendering when a click handler is present.  I broke this functionality when I added the `UnstyledButton` as part of this PR: https://github.com/CareEvolution/MyDataHelpsUI/pull/176
- No security risk.  Just a small rendering adjustment.

Fix calendar day rendering.

---

src/components/container/InboxItemList/InboxItemList.tsx
src/components/view/InboxView/InboxView.tsx

I missed a couple of import updates before merging https://github.com/CareEvolution/MyDataHelpsUI/pull/189.
- No new security risks.

Inbox UI: Fix a couple of imports.

---

package-lock.json
package.json
src/components/container/BloodPressureVisualization/BloodPressureVisualization.css
src/components/container/BloodPressureVisualization/BloodPressureVisualization.stories.tsx
src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx
src/components/container/SeverityCalendar/SeverityCalendar.css
src/components/container/SeverityCalendar/SeverityCalendar.tsx

- The date navigator on the Blood Pressure Visualization was replace with a date coordinator. Stories were updated to adjust for this change. 
- Severity and BP Visualizations will show a 'Not Supported' message when the date coordinator is not configured to the supported interval type
- [ x] I have ensured no secure credentials or sensitive information remain in code, metadata, comments, etc.
- [x ] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [x ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [ x] These changes do not introduce any security risks, or any such risks have been properly mitigated.
Describe …

Data visualizations Changes

---

src/helpers/globalCss.ts

Believe this is the correct magic spell such that dynamic text size still works on iOS/Android and the base font size is set to 17px.  Previously, Safari desktop base font size was getting reset to 13px.

Fix small font size in safari

---

src/components/container/BloodPressureVisualization/BloodPressureVisualization.stories.tsx
src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx
src/helpers/blood-pressure-data-providers/combined-blood-pressure-data-provider.ts
src/helpers/blood-pressure-data-providers/device-blood-pressure-data-provider.ts
src/helpers/blood-pressure-data-providers/index.ts
src/helpers/blood-pressure-data-providers/survey-blood-pressure-data-provider.ts

Add AppleHealth and GoogleFit data to the BloodPressureVisualization.
When a survey data source is specified, give the option to hide AppleHealth & GoogleFit data
- [x ] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [x ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [ x] These changes do not introduce any security risks, or any such risks have been properly mitigated.
This updates an existing …

Add AppleHealth & Google Fit data to the Blood Pressure Visualization

---

src/components/container/RecentDailyDataBarChart/RecentDailyDataBarChart.tsx

The `RecentDailyDataBarChart` has a bug where the day tick labeling is incorrect when crossing month boundaries.  This branch fixes that.
n/a

Fix an issue with RecentDailyDataBarChart dayTick rendering around month boundaries.

---

src/stories/Introduction.stories.mdx

Spelling fix.  Addresses https://github.com/CareEvolution/MyDataHelpsUI/issues/183
No risks - spelling changes only
(N/A)
(N/A)

Spelling update on Introduction Story

---

src/components/container/DeviceDataMonthChart/DeviceDataMonthChart.tsx
src/helpers/strings-en.ts
src/helpers/strings-es.ts

Added two Spanish translations for the Device Data Month Chart.  Addresses: https://github.com/CareEvolution/MyDataHelpsUI/issues/221
Translations are from google translate:
`No Data` => `Sin Datos`
`Daily Average` => `Promedio Diario`
Note:  The titles, `"Resting Heart Rate"` and `"Steps"`, are passed in and should be localized prior to invoking this widget.
Updates only for the UI, and only for language display.
Tested via Storybook, by changing browser language to Spanish.
Not Applicable 
Assign to the appropriate reviewer(s). Minimally, a second set of …

Add Spanish translations for Device Data Month Chart

---

src/components/presentational/DateRangeCoordinator/DateRangeCoordinator.stories.tsx
src/components/presentational/DateRangeCoordinator/DateRangeCoordinator.tsx
src/components/presentational/DateRangeNavigator/DateRangeNavigator.stories.tsx
src/components/presentational/DateRangeNavigator/DateRangeNavigator.tsx

Add Day navigation to the DateRangeNavigator and DateRangeCoordinator
- [x ] [MyDataHelps website](mydatahelps.org)

Add Day navigation to the DateRangeNavigator and DateRangeCoordinator

---

src/components/asthma/views/AsthmaActivityView/AsthmaActivityView.tsx
src/components/asthma/views/AsthmaAirQualityView/AsthmaAirQualityView.tsx
src/components/asthma/views/AsthmaDayView/AsthmaDayView.tsx
src/components/asthma/views/AsthmaHeartAndLungsView/AsthmaHeartAndLungsView.tsx
src/components/asthma/views/AsthmaProviderReportView/AsthmaProviderReportView.tsx
src/components/asthma/views/AsthmaSleepView/AsthmaSleepView.tsx
src/components/presentational/NavigationBar/NavigationBar.css
src/components/presentational/NavigationBar/NavigationBar.tsx
src/components/view/ResourceListView/ResourceListView.tsx

Fixes an issue with top padding of navigation bar children that I introduced a while back when updating the navigation bar.
https://github.com/CareEvolution/MyDataHelpsUI/commit/17a361cabb9f41e56c49c8cc0e240ef9e97e78a4#r140349783
- No security risk.  Just adjusting some CSS padding within the Navigation Bar component.

Fix an issue with the top padding of navigation bar children.

---

src/helpers/blood-pressure-data-providers/survey-blood-pressure-data-provider.ts

BP Visualization - support survey data without requiring result id for the date observed. When a result id for the date observed is not supplied, the date the answers were recorded will be used. 
- [ x] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [x ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [ x] These changes do not introduce any security risks, or any such risks have been properly mitigated.
Describe briefly what security risks you considered, why they don't apply, or how they've been …

BP Viz - do not require a date result id

---

src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx
src/helpers/strings-de.ts
src/helpers/strings-en.ts
src/helpers/strings-es.ts
src/helpers/strings-fr.ts
src/helpers/strings-it.ts
src/helpers/strings-nl.ts
src/helpers/strings-pl.ts
src/helpers/strings-pt.ts

Create a blood pressure survey and submit the following multiple entries for a single day  (systolic/diastolic)
1. 80/60
2. 120/80
3. 40/40
4. 20/40
Current Behavior
The bottom right cube shows Lowest Diastolic with a value of 40
All other aggregate values are correct
Expected Behavior
The bottom right cube shows the Lowest Systolic with a value of 20
All other aggregate values are correct
- [ x] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
- [x ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [x ] …

Fix: Blood Pressure Visualization bottom right cube should show Min Systolic

---

.storybook/preview.js

Previously, calling setCurrentLanguage with the empty string generates a console warning and fails to clear the language.  
Instead, we manually set MyDataHelps.language to the empty string and do not call setCurrentLanguage.  This allows future calls of MyDataHelps.getCurrentLanguage() to return the browser default language.
No security risks, client side code changes only.

Validate language before calling setCurrentLanguage

---

src/components/container/RestingHeartRateCalendar/RestingHeartRateCalendar.stories.tsx
src/components/container/RestingHeartRateCalendar/RestingHeartRateCalendar.tsx
src/helpers/daily-data-providers/apple-health-sleep.ts
src/helpers/daily-data-providers/combined-resting-heart-rate.ts

Updates the combined RestingHeartRate data provider to look at Garmin data, as well as AppleHealth and Fitbit.  It will then average and round the combined results for each day.  ~~Added stories to the Resting Heart Rate Calendar container for each three individual data sources as well as the combined data source.~~  Added a "Live" story that defaults to the Combined datasource, with options to selected a specific datasource.
Addresses https://github.com/CareEvolution/MyDataHelpsUI/issues/101
Test data for these screenshots was: no AppleHealth rhr data, fitbit data for one day, and garmin data for two days.
No security risks, UI changes only. …

RestingHeartRate - add garmin

---

src/components/asthma/components/AsthmaPostEnrollmentSurveyTrigger/AsthmaPostEnrollmentSurveyTrigger.tsx
src/components/asthma/helpers/asthma-data.ts

This branch updates the Asthma post enrollment survey trigger component to additionally auto-launch the today logging survey one time if all other post enrollment surveys have been completed and no logs have yet been recorded.
- No security risk.  Just auto-launching the logging survey that is already available to the user when specific conditions are met.
n/a

Asthma: Auto launch logging one time after post enrollment activities have been completed.

---

src/components/container/RelativeActivity/RelativeActivity.tsx

Fixes a minor regression where the "relative activity" component was not properly filtering out 0 / empty values.  Also in my testing I saw the potential for requests to return out of order here; followed a similar pattern to providerSearch to prevent this from happening. 

Fix relative activity showing 0s

---

src/components/container/AppDownload/AppDownload.tsx

Because app download has a wrapper div around the ```<PlatformSpecificContent>``` that wrapper div was being output even when the component should be entirely hidden.
This can result in showing a 0-height card or section if the AppDownload is the only child of that card/section
- [ x There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- …

Fix app download height when not shown

---

src/components/container/SurveyAnswerChart/SurveyAnswerChart.tsx

Small update to ensure that the Survey Answer Chart renders the most recent answer from a given day when more than one answer exists.
- No new security risk.  Just fixes the selection process for the answer to render for a given day.
- N/A

Update survey answer chart answer selection to prefer the latest answer per day.

---

src/components/container/SurveyAnswerChart/SurveyAnswerChart.stories.tsx
src/components/presentational/TimeSeriesChart/TimeSeriesChart.stories.tsx
src/components/presentational/TimeSeriesChart/TimeSeriesChart.tsx

Recharts has trouble rendering bar graphs on number based x-axis lines when there's only one data point.  It fails to properly calculate the width of the bar (https://github.com/recharts/recharts/issues/3640) as well as the gap between the x-axis and the first tick.  
While Recharts has provided some theoretical tools to help (letting you manually set the width, or manually set the padding), it turns out that for this edge case a trivial solution is to pad the data with a null data point at an expected interval.  
There's a very minor visual artifact of this if you're on desktop and can hover the chart; you get a line where it attempts to put a tooltip for the data point, but no tooltip displays.  This is the same artifact that you get on a line chart where we need to enforce a "gap" in …

Fix Recharts Bar graph edge case

---

src/components/container/MealEditor/MealEditor.tsx

A recent [change to support better date/time localization](https://github.com/CareEvolution/MyDataHelpsUI/pull/367/files#diff-f912f9d7e60086d38b3d51ea89997c2a904b2e97a0eaab91f269bdb2cac21245R201) caused an issue with the `MealEditor`'s time input field.  The HTML time input field requires a specific canonical format for the values, so it was no longer rendering the values.  I have reverted that change with a slight modification to use the specific format (`HH:mm`), regardless of locale.
- No security risk.  Just correcting and issue with time input value setting.
- N/A

Fix MealEditor time input value population.

---

src/components/container/MostRecentNotification/MostRecentNotification.previewdata.tsx
src/components/container/MostRecentNotification/MostRecentNotification.stories.tsx
src/components/container/MostRecentNotification/MostRecentNotification.tsx
src/components/presentational/SingleNotification/SingleNotification.tsx
src/components/view/HomeView/HomeView.tsx

This is a change needed for IHS 2025.
This adds a new property to the MostRecentNotification component: A regex string that will filter the notifications. It works like the NotificationList component.
One major change I had to make here was how we fetched notifications. If the notification identifier regex is supplied, we have to query until something matches or we run out of results.
Another change I made here is brough the storybook for this component up to date. I followed the example set by NotificationList component.
Assign to the appropriate reviewer(s). Minimally, a second set of eyes is needed ensure no non-public information is published. Consider also …

MostRecentNotification: Add identifier regex filter

---

src/components/container/ProviderSearch/ProviderSearch.previewdata.tsx
src/components/container/ProviderSearch/ProviderSearch.stories.tsx
src/components/container/ProviderSearch/ProviderSearch.tsx

This branch updates the `ProviderSearch` component's "request add" functionality to handle additional category configuration scenarios.  Specifically, what to do when the "Device Manufacturer" category is solely or also present, and what to do when multiple "add-able" categories are present.
- No security risk.  Just adjusting when and what gets displayed on the "request add" button with some additional category configuration scenarios.

Update the ProviderSearch "request add" functionality to handle additional category configuration scenarios.

---

src/components/container/BloodPressureVisualization/BloodPressureVisualization.tsx

I think we need to use DumbBellDataPoint instead of DumbBell
Related to https://github.com/CareEvolution/MyDataHelpsUI/pull/385

Fix errors due to importing DumbBell

---

__tests__/helpers/locale/date-helpers.test.ts
src/components/container/GlucoseChart/GlucoseChart.tsx
src/components/presentational/TimeSeriesChart/TimeSeriesChart.tsx
src/helpers/date-helpers.ts

Times in the time series chart (used in GlucoseChart)  are squished in:
* 12-hour time format locales (e.g., en-US)
* mobile width
* "Day" `intervalType` option (for hours of the day)
Fix was adding a new "short time of day" format that appears as "6 AM" in 12-hour locales and "06:00" in 24-hour ones.
**Testing Notes**
* Date/time formats are governed by the browser's language setting, not the language dropdown.
* Test both `TimeSeriesChart` and `GlucoseChart`. I didn't see anywhere else using TimeSeriesChart with a custom tickFormatter.
Assign to the …

Fix Times in Time Series Chart

---

src/helpers/daily-data-providers/common-mindful-and-therapy.ts

Fixes a bug with Apple Health SilverCloud CBT data point filtering.
The `Metadata_sub-type` property exists on the SilverCloud CBT data points, not on their data sources.
- N/A

Fix the AppleHealth therapy minutes CBT data point filter.

---

src/components/presentational/NavigationBar/NavigationBar.css

When there is no title/subtitle in the navigation bar, it was getting squished like this:
This is because 1) the nav bar uses box-sizing border-box and 2) the top padding adds the safe-area-inset-top (which is like 90px or something on iOS), and the only thing causing the nav bar to have height was min-height:56px, which was essentially irrelevant because of 1/2.
Easy solution is to incorporate the safe area calculation into the min-height.
I have verified this fix in the iOS safari debugger.
Assign to the appropriate reviewer(s). Minimally, a second set of …

Fix nav bar height when no title / subtitle

---

src/components/container/RelativeActivityDayCoordinator/RelativeActivityDayCoordinator.tsx

This fixes a bug with the relative activity day coordinator.  The intent was that if you do not have data for a particular data type, it would just not show up in this view; for instance we might include a bunch of data types from Fitbit, Garmin, Apple Health ,etc. but they would only show if you had data.  
However, the bars were just rendering based on props.datatypes rather than availableDataTypes, so it would awkwardly look like this:
This fixes it to use availableDataTypes 
Assign to the appropriate reviewer(s). Minimally, a second set of eyes is needed …

Fix relative activity bars if no available data

---

src/components/presentational/NavigationBar/NavigationBar.css

Another nav bar issue.
The nav bar children has safe area padding added to the top of it, which is redundant because it's already added to the navigation bar itself.  Ends up giving it a ton of extra space:
This removes that extra padding.  I think this mostly affects the EHR views as they follow this pattern.

Fix the giant navigation bar

---

package-lock.json
package.json
src/components/presentational/InboxSurveyListItem/InboxSurveyListItem.stories.tsx
src/components/presentational/InboxSurveyListItem/InboxSurveyListItem.tsx

This branch updates the `InboxSurveyListItem` to render the survey's `displayName` rathan than its `name`, when available.
Updates MDH-JS to `v3.29.0` to bring in the new `displayName` field.
Related to https://github.com/CareEvolution/Consumers/pull/12934.
- No new security risks.  Just prioritizing using the display name over the regular name when rendering Inbox survey CTAs.

InboxSurveyListItem: Render using the survey's displayName when available.

---

src/components/container/InboxItemList/InboxItemList.tsx

This branch adds a temporary fix for `InboxSurvey` launching to handle situations where the survey display name does not match the survey name.
At present, the Inbox API returns the display name in `InboxSurvey` items.  If that differs from the actual name of the survey, the survey fails to launch.  This temporary fix performs a query for the participant's incomplete survey tasks in order find the correct survey name to use when launching the `InboxSurvey`.
This change will be reverted once the Inbox API and relevant model classes have been updated to include both the name and the display name.
- No new security risk.  This update uses an …

Temporary fix for Inbox survey launching.

---

package-lock.json
package.json
src/components/presentational/Grid/Grid.css
src/components/presentational/Grid/Grid.stories.tsx
src/components/presentational/Grid/Grid.tsx

Turns out my fancy CSS rules for hiding grid columns if there's just an empty card child causes some major issues in iOS safari.
Unfortunately it looks like there's not much of an elegant solution to the whole "hide an element if it's children are hidden" problem, without implementing a whole lot of "onVisible" props or something.  I would definitely like to avoid that.
So this tackles it a bit of a different way by having a "Card" variant for "GridColumn".  This means that Grid columns themselves can just render as cards, which of course already hide themselves if they are empty via the tried and true ```:empty``` css selector
Consider "Squash …

Fix MicroTrend Grid

---

src/components/view/ConnectDevicesView/ConnectDevicesView.tsx

This is a follow up to #423.  I missed that we want to be able to set this via the prebuilt `ConnectDevicesView` and pass the parameter through to the `ConnectDevicesMenu`.

Allow setting of Postal Code Survey in Connect Devices View

---

__tests__/helpers/glucose-and-meals/meals.test.ts
src/components/container/MealEditor/MealEditor.tsx
src/components/presentational/MealButtons/MealButtons.tsx
src/helpers/glucose-and-meals/meals.ts
src/helpers/glucose-and-meals/types.ts

This branch adds `created` and `lastModified` dates to meals.  These dates are not being rendered anywhere in the existing meal components, but we have a use case that would like to have this information downstream.
- No security risk.  Just adding a couple more date fields to the existing Meals model.
- N/A

Add meal created and last modified dates.

---

src/components/container/ConnectDevicesMenu/ConnectDevicesMenu.tsx

Omron used to not have a feature flag so it operated weirdly and was only included in the connect devices menu when explicitly specified.
Now that it does, it can work consistently with fitbit, garmin, etc. so this does that

Add Omron to connect devices menu by default

---

.github/workflows/cicd-release.yml
.github/workflows/cicd-snapshot.yml

Move the github actions from 17.3.0 to 20.x
bumping the node version
> Consider whether the changes might have device-specific behaviors (screen padding, new APIs, etc.) and check one of the following boxes:
NA
> Consider whether there are any documentation impacts and check one of the following boxes:

use 20.x for the GH actions

---

.github/workflows/build-and-test-workflow.yml
package-lock.json
package.json

The GH release action was failing with an error
```
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
at requireWithFriendlyError (/home/runner/work/MyDataHelpsUI/MyDataHelpsUI/node_modules/rollup/dist/native.js:63:9)
```
I am guessing it was something in here https://github.com/CareEvolution/MyDataHelpsUI/pull/402 related to storybook?
Two changes to address this:
- add the rollup step to the build-and-test workflow so that these sorts of errors will be found earlier in our process. 
- to address the problem it adds @rollup/rollup-linux-x64-gnu as an optional dependency 
> Consider potential security …

Add optional lib for rollup on linux

---

__tests__/helpers/time-range.test.ts
src/helpers/time-range.ts

This branch fixes an issue that I discovered while testing the latest VB upgrade.
I had recently updated the sleep de-duplication and overlap code to account for the V2 data and its date offsets.  However, there was a bug I missed with the parsing when the offset does not contain a sign (i.e. `00:00:00` rather than `-04:00:00`).
It was also brought to my attention recently that we should be ignoring the offsets from V2, since all of the dates are in local time, and that is how we want to chart/present them anyways.  As such, rather than attempting to fix the parsing logic here, I've just updated the code to ignore the V2 date offsets, which is the desired behavior. …

Fix issue with sleep V2 date parsing.

---

src/components/presentational/TimeSeriesChart/TimeSeriesChart.tsx

> Explain your changes, including any issues or relevant context about why they are needed.
We have discovered a bug where the dots in line graphs on either end of the axis are being clipped
This is related to the `allowDataOverflow` on the YAxis property. @ajmenca found a [PR that fixed the issue](https://github.com/recharts/recharts/pull/3602) merged into recharts. This adds a new (undocumented 😟) property to the Dot element called `clipDot`. When you set this to false, the dot now renders correctly
From the recharts PR: 
> When `allowDataOverflow` is true on `XAxis` or `YAxis`, set `clipDot` within the dot object to determine if recharts should clip the dots at the end of the page.
> **REMINDER:** All file …

Fix dot clipping

---

package-lock.json
package.json
src/components/container/ConnectDevicesMenu/ConnectDevicesMenu.tsx

Closes https://github.com/CareEvolution/MyDataHelpsViewBuilder/issues/262
Connect Devices Menu was not refreshing on web after connecting to Oura/Fitbit/Garmin.  This worked fine on iOS/Android because applicationDidBecomeVisible gets triggered, but on web we need to handle the result of the connectExternalAccount action promise to refresh
This was slightly awkward because I use a hook for the state here; I ended up passing a "refresh" function out of the hook so that it could be called by the component, which makes sense to me, but not sure if there's a better convention
Just a bugfix
> Consider whether the changes might have device-specific behaviors (screen …

Connect devices menu refresh

---

src/components/container/ProviderSearch/ProviderSearch.tsx

Our public provider search endpoint uses 1-based paging.  This branch adjusts the value used by the `ProviderSearch` component to avoid loading the first page from the public endpoint twice.
DESCRIBE BRIEFLY WHAT SECURITY RISKS YOU CONSIDERED, WHY THEY DON'T APPLY, OR HOW THEY'VE BEEN MITIGATED.
- No new security risk.  Just fixing a bug that causes the first page of providers from the public endpoint to load twice.
> Consider whether the changes might have device-specific behaviors (screen padding, new APIs, etc.) and check one of the following boxes:
DESCRIBE YOUR TEST PLAN
- Open the "Public Endpoint" storybook story for the `ProviderSearch` component.  Verify that …

ProviderSearch: Fix the public provider endpoint page numbers.

---

src/components/step/ConnectEhrStep/ConnectEhrStep.css
src/components/step/ConnectEhrStep/ConnectEhrStep.tsx
src/components/step/StepLayout/StepLayout.tsx
src/components/step/StepNextButton/StepNextButton.css

- Button was moved to a fixed position in #100, to work properly with an infinite scroll so that the button wasn't pushed off the screen constantly by the new data.
- This broke the layout of the YouTube step, content would end up behind the button (the story was obviously broken and it wasn't noticed in review of #100):
- Also technically didn't work correctly in all cases anyway; if the list stopped loading, the last rows would be behind the button.
- Revert button to inline-block by default, customize only for ConnectEhrStep; fix ConnectEhrStep by adding margin-bottom so next button doesn't obscure content.
N/A; styling changes only.
> Consider whether the changes …

Fixed button placement was blocking content

---

__tests__/components/asthma/helpers/daily-data-providers/shared.test.ts
src/components/asthma/helpers/daily-data-providers/shared.ts

> Explain your changes, including any issues or relevant context about why they are needed.
Small bug fix.  I was passing the arguments to the `date-fns` `isAfter` function in the wrong order.
DESCRIBE BRIEFLY WHAT SECURITY RISKS YOU CONSIDERED, WHY THEY DON'T APPLY, OR HOW THEY'VE BEEN MITIGATED.
- No security risk.  Just a sorting/selection bug fix.
- Unit test added.
> Consider whether there are any documentation impacts and check one of the following boxes:

Asthma: Fix device data date comparison.

---

src/components/presentational/TimeSeriesChart/TimeSeriesChart.tsx

> Explain your changes, including any issues or relevant context about why they are needed.
The 6 month view for a Time Series chart was only showing 5.5 months.  This was caused by the tick generation for the X-Axis.  In generating ticks only a the 1st and 15th of the month, the interval was stopping on the 1st of the next month, but not actually pushing a tick for it, which meant that the last tick was the 15th of the last month.  This meant that the graph wasn't ever showing data between the 15th and the end of the month.
A graph generated for today, 5/28:
DESCRIBE BRIEFLY WHAT SECURITY RISKS YOU CONSIDERED, WHY THEY DON'T APPLY, OR HOW THEY'VE BEEN MITIGATED.
> …

Fix missing final tick for a 6 month view

---

package-lock.json
package.json
src/components/container/ProviderSearch/ProviderSearch.previewdata.tsx
src/components/container/ProviderSearch/ProviderSearch.stories.tsx
src/components/container/ProviderSearch/ProviderSearch.tsx
src/components/container/ProviderSearch/index.ts
src/components/step/ConnectEhrStep/ConnectEhrStep.tsx
src/helpers/public-providers.ts

This branch updates the `ProviderSearch` component to adjust how featured providers are supported.  It also introduces an "operating mode" concept and corrects a couple of timing/closure related bugs I found with paging while working on that update.
The storybook entries for the `ProviderSearch` were also overhauled.
This new property can be set to `authenticated` or `unauthenticated`.  If not specified, it will default to `authenticated` unless either the `publicProviderSearchApiUrl` or `publicFeaturedProvidersApiUrl` URLs are set.  In that case, it will default to `unauthenticated`.
In `authenticated` mode, the component will use the delegated APIs to load featured providers (if they have not been manually set), search for providers, and load existing external accounts.
In …

ProviderSearch: Operating mode, updated featured provider support, and a couple bug fixes.

---

src/helpers/daily-data-types/combined.tsx

> Explain your changes, including any issues or relevant context about why they are needed.
During some data provider testing, I noticed that the combined steps data provider availability sources were not correct.
While adding the new HC steps data provider https://github.com/CareEvolution/MyDataHelpsUI/pull/483, I forgot to update the sources.
I also noticed that the Oura source was missing from the one definition and was incorrect in the other, so that has been fixed as well.
DESCRIBE BRIEFLY WHAT SECURITY RISKS YOU CONSIDERED, WHY THEY DON'T APPLY, OR HOW THEY'VE BEEN MITIGATED.
- No new security risk.  Just fixing the data types the combined steps provider will …

Correct the combined steps availability check sources.

---

package-lock.json
package.json
src/components/container/IntradayHeartRateChart/IntradayHeartRateChart.previewdata.ts
src/components/container/MostRecentNotification/MostRecentNotification.previewdata.tsx
src/components/container/NotificationList/NotificationList.previewdata.tsx
src/components/container/NotificationList/NotificationList.stories.tsx
src/components/container/SeverityCalendar/SeverityCalendar.previewdata.tsx
src/components/container/SurveyAnswerChart/SurveyAnswerData.previewdata.tsx
src/components/container/SurveyTaskList/SurveyTaskList.previewdata.tsx
src/components/presentational/DateRangeCoordinator/DateRangeCoordinator.stories.tsx
src/components/presentational/SingleNotification/SingleNotification.stories.tsx

I would like to bump the MDH-JS version to the latest (v5.0.0).
Here is the diff: https://github.com/CareEvolution/MyDataHelps.js/compare/v4.2.1...v5.0.0
Notable Updates:
- Some clerical changes to the PR template, README, etc, which are not applicable to MDH-UI.
- Support for passing optional `editResultID` and `event` options to the `MyDataHelps.startSurvey(...)` function.
- A new function to acquire the list of all supported V1 data types.
- An update to the V2 data types function to allow for filtering by namespace.
- Some type definition updates to get the type definitions in sync with our APIs.
The majority of the changes are backward compatible, with no change to existing functionality.  The type definition changes did required some updates to sample data creation across a number …

Bump MDH-JS to the latest version.

---

src/components/container/DocumentLibraryPreview/DocumentLibraryPreview.css
src/components/container/DocumentLibraryPreview/DocumentLibraryPreview.stories.tsx
src/components/container/DocumentLibraryPreview/DocumentLibraryPreview.tsx

This branch includes a couple minor adjustments to the document library preview component.
- By default, the component renders with a small internal spinner while loading.  We have a need to use this component downstream along side a bunch of sibling components that all render as spinners only while loading.  I've added an optional flag named `useFullLoadingIndicator` which tells this component to render as a spinner only while loading.
- The upload button was rendering over the text when the component was being used at mobile width.  To fix this, I set the indicator position back to the default, so it would render inline instead of absolutely, which fixes the overlapping issue.
> **REMINDER:** All file contents …

Couple minor adjustments to the document library preview component.
